angular.module('Ticket',['ngRoute'])
.config(function($routeProvider)
{
    $routeProvider.when('/Home',
    {
        templateUrl:'SiglePage_Home.html',
        controller:'homectrl'
    }).when('/Reports',
    {
        templateUrl:'SinglePage_Report.html',
        controller:'reportsctrl'
    }).when('/Documents',
    {
        templateUrl:'SiglePage_Documents.html',
        controller:'Ticket_ctrl'
    }).when('/Home/:First/:Last',
    {
        templateUrl:'SiglePage_Home.html',
        controller:'homectrl'
    })
})
.controller('myctrl',function()
{

})
.controller("homectrl",function($scope,$routeParams)
{
    $scope.message="Ticket Page"
    if($routeParams.First&&$routeParams.Last)
    {
        $scope.person={
            First:$routeParams.First,
            Last:$routeParams.Last
        };
    }
})
.controller("Ticket_ctrl",function($scope,$http)
{
    $http.get('https://ankurs11.github.io/JSON/data.json')
    .success(function(response)
    {
        $scope.ticket_details=response.records;
    });
})
.controller("reportsctrl",function($scope,$http)
{
    $http.get('data.json')
    .success(function(response)
    {
        $scope.ticket_data=response.records;
    });
});